version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: 'howOld'
      POSTGRES_PASSWORD: 'howOld'
    ports:
      - 5433:5433
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
volumes:
  postgresql-data:
